### ISSUE TITLE
Export Options

### ISSUE THREAD

**Issue by Drache93** [DKesserich/Better-Collada-Exporter-HW-Edition-#3]
Are all the export options actually important for HW, or can they be hidden?

**Comment by DKesserich** [comment]
Since I never really touched what got pulled in from the options, I'm worried that removing or hiding the options might break a bunch of dependencies in the export script, so I'd rather just leave that all alone.

**Comment by Drache93** [comment]
True point, I think simply hiding the options is less simple in blender so you're right. My one concern is if anyone changes the settings. Not really worth the effort considering the unlikelyness of issues.
