### ISSUE TITLE
Weapon Mesh

### ISSUE THREAD

**Issue by Drache93** [DKesserich/Better-Collada-Exporter-HW-Edition-#7]
Can't think of any real uses at the moment - some things may need it; but generally said every hierarchy (docking, ROOT etc.) is predictable.

**Comment by Drache93** [comment]
Will be replaced with a quick check for "ROOT_LOD[0]" with a pop up message if not found.
Thoughts?

**Comment by DKesserich** [comment]
That sounds good. Though there's some stuff with the hierarchy for turrets that might be tricky. In the Multi-gun Corvette example the Weapon Position groups are children of the Root Joint, but there are also some additional joints that are children of the Ship joint.

**Comment by Drache93** [comment]
Those seem to be linking back to MESHs in the gun joints - additional models. Worth checking if they change at all during shooting (move etc.). But by the looks of things it's a simple way of linking additional meshes back to the main one. Can't see any real reason why though other than ease of editing. Maybe they appear during upgrades? - i don't know off the top of my head, will check the .ship.

**Comment by Drache93** [comment]
Based off of the locations of the joints I'm assuming the model moves with the weapon tracking - so the weapon's built in angle limiters will be what limits the model movement.

**Comment by Drache93** [comment]
Yep, tested. those models move at the joints. Still assuming it's the weapon file that controls the limits - only option to be fair.

**Comment by Drache93** [comment]
Checked. Individual weapons for the front guns and side ones.
Any idea what the XYZ is in this?
"setAngles(NewWeaponType,0,-34,34,-18,18);"

Some weapons have a number for the first value.
I'm thinking...hard rotation for the first one (-180 flips the weapon), then the other 4 are the limits for Z and X rotation. So the fun is free to move -34 -> +34 on the Z axis (made sense in 3ds Max; 34 is too much freedom on X axis).

**Comment by DKesserich** [comment]
http://hw2wiki.net/wiki.hw2.info/FunctionsetAngles.html

First value is firing cone (so at 0 it'll only fire when the target is straight ahead), then minmax azimuth, minmax declination. I guess the location of the latitude node is how it determines azimuth and declination.

**Comment by Drache93** [comment]
Added in. Still to be tested ingame, but everything straight copy from original (minus scar flag atm).
Added like normal weapon, but requires a model to be selected.
Best practice is to make a weapon model, change it's pivot point (ctrl-shift-alt-c) then use the tool to attach it to your 3d cursor.

Currently - forgot to fix (going to bed) - weapon gets flipped 90 degrees and required flipping back the mesh (not object).

**Comment by Drache93** [comment]
According to the MultiGun model, latitude is supposed to be a parent of muzzle FYI/self reminder.
